apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis01-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: redis01
  template:
    metadata:
      labels:
        app: redis01
    spec:
      containers:
        - name: redis01
          image: redis:3
