apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-worker
  template:
    metadata:
      labels:
        app: vote-worker
    spec:
      containers:
      - name: vote-worker
        image: irkhamdayat/vote-worker-image:1.0
        env:
          - name: FROM_REDIS_HOST
            value: "1"
          - name: TO_REDIS_HOST
            value: "1"
          
